from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import html
from typing import Iterable

from .config import DailyPaperConfig
from .fetch import FeedEntry
from .summarize import SummarizedItem, TopicSummary
from .utils import format_published


@dataclass
class RenderContext:
    config: DailyPaperConfig
    generated_at: datetime
    sources_checked: int
    paywalled_excluded: int
    topic_summaries: dict[str, TopicSummary]
    items_by_topic: dict[str, list[SummarizedItem]]


def render_html(context: RenderContext) -> str:
    config = context.config
    sections = "\n".join(
        render_topic_section(
            topic,
            context.topic_summaries.get(topic),
            context.items_by_topic.get(topic, []),
            config,
        )
        for topic in context.items_by_topic
    )

    footer = (
        f"Generated {context.generated_at.strftime('%Y-%m-%d %H:%M:%S')} "
        f"local time. Sources checked: {context.sources_checked}. "
        f"Paywalled items excluded: {context.paywalled_excluded}. "
        f"<a href=\"archive/index.html\">Archive</a>."
    )

    return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
  <meta
    http-equiv=\"Content-Security-Policy\"
    content=\"default-src 'none'; style-src 'unsafe-inline'; img-src 'none'; script-src 'none'; font-src 'none'; connect-src 'none'; base-uri 'none'; form-action 'none'\"
  />
  <title>The Daily Signal — An AI-generated, impartial digest</title>
  <style>
    :root {{
      color-scheme: light;
      --ink: #1d1b16;
      --muted: #5a544a;
      --paper: #f8f3e8;
      --rule: #c9c2b8;
    }}
    body {{
      margin: 2.5rem auto;
      max-width: 1040px;
      padding: 0 1.5rem;
      font-family: "Iowan Old Style", "Palatino Linotype", "Book Antiqua", Georgia, "Times New Roman", serif;
      line-height: 1.75;
      color: var(--ink);
      background: var(--paper);
      text-align: justify;
    }}
    header {{
      text-align: center;
      border-bottom: 2px solid var(--rule);
      padding-bottom: 0.85rem;
      margin-bottom: 1.5rem;
    }}
    h1 {{
      font-size: 2.1rem;
      letter-spacing: 0.08em;
      text-transform: uppercase;
      margin: 0;
    }}
    .tagline {{
      margin: 0.35rem auto 0;
      max-width: 52rem;
      color: var(--muted);
      font-size: 0.98rem;
    }}
    .paper-meta {{
      margin-top: 0.55rem;
      font-size: 0.85rem;
      color: #7a7266;
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }}
    main {{
      column-count: 2;
      column-gap: 2.5rem;
    }}
    @media (max-width: 900px) {{
      main {{
        column-count: 1;
      }}
    }}
    /* Keep topics intact inside the two-column layout for easier scanning. */
    section {{
      break-inside: avoid;
      margin-bottom: 2.5rem;
    }}
    h2 {{
      font-size: 1.35rem;
      margin-bottom: 0.5rem;
      border-bottom: 1px solid var(--rule);
      padding-bottom: 0.3rem;
    }}
    p {{
      margin: 0.6rem 0;
    }}
    .item {{
      margin-bottom: 1.2rem;
    }}
    .meta {{
      color: var(--muted);
      font-size: 0.9rem;
    }}
    .macro-watch {{
      border: 1px solid var(--rule);
      padding: 0.6rem 0.8rem;
      background: #fbf7ee;
      font-size: 0.95rem;
    }}
    .macro-watch div + div {{
      margin-top: 0.35rem;
    }}
    footer {{
      margin-top: 3rem;
      padding-top: 1.5rem;
      border-top: 1px solid var(--rule);
      font-size: 0.9rem;
      color: var(--muted);
      text-align: center;
    }}
  </style>
</head>
<body>
  <header>
    <h1>The Daily Signal</h1>
    <p class=\"tagline\">
      A calm, fact-first newspaper generated by AI to summarize the day without
      sensationalism or editorial bias.
    </p>
    <div class=\"paper-meta\">Independent digest · Updated daily</div>
  </header>
  <main>
    {sections}
  </main>
  <footer>
    {footer}
  </footer>
</body>
</html>"""


def render_topic_section(
    topic: str,
    summary: TopicSummary | None,
    items: Iterable[SummarizedItem],
    config: DailyPaperConfig,
) -> str:
    summary_html = render_macro_watch(summary)

    items_html = "\n".join(
        render_item(item, topic) for item in items
    )

    return f"""
<section id=\"{slugify(topic)}\">
  <h2>{escape_html(topic)}</h2>
  {items_html}
  {summary_html}
</section>
"""


def render_item(item: SummarizedItem, topic: str) -> str:
    entry = item.entry
    published = format_published(parse_iso(entry.published))
    meta_parts = [escape_html(entry.source)]
    if published:
        meta_parts.append(published)
    meta = " · ".join(meta_parts)

    summary_text = escape_html(item.summary)
    if topic == "Tech News":
        label = label_for_entry(entry)
        summary_text = f"{label} {summary_text}"

    return f"""
<div class=\"item\">
  <div>{summary_text}</div>
  <div class=\"meta\">{meta} · <a href=\"{escape_html(entry.link)}\">Source</a></div>
</div>
"""


def parse_iso(value: str) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


def slugify(text: str) -> str:
    return "".join(ch.lower() if ch.isalnum() else "-" for ch in text).strip("-")


def escape_html(text: str) -> str:
    return html.escape(text, quote=True)


def render_macro_watch(summary: TopicSummary | None) -> str:
    if not summary:
        macro_line = "Macro: Not enough accessible detail to synthesize."
        watch_line = "Watch: Next release / official update."
        return (
            "<div class=\"macro-watch\">"
            f"<div>{escape_html(macro_line)}</div>"
            f"<div>{escape_html(watch_line)}</div>"
            "</div>"
        )
    lines = [line.strip() for line in summary.summary.splitlines() if line.strip()]
    if len(lines) >= 2:
        macro_line = lines[0]
        watch_line = lines[1]
    else:
        macro_line = "Macro: Not enough accessible detail to synthesize."
        watch_line = "Watch: Next release / official update."
    return (
        "<div class=\"macro-watch\">"
        f"<div>{escape_html(macro_line)}</div>"
        f"<div>{escape_html(watch_line)}</div>"
        "</div>"
    )


def label_for_entry(entry: FeedEntry) -> str:
    feed_name = (entry.feed_name or entry.source or "").strip()
    lower_name = feed_name.lower()
    if "cloudflare changelog" in lower_name:
        return "[DevOps]"
    if "security" in lower_name:
        return "[Security]"
    if entry.feed_category == "AI":
        return "[AI]"
    if entry.feed_category == "Web":
        return "[Web]"
    if "devops" in lower_name or "infrastructure" in lower_name or "performance" in lower_name:
        return "[DevOps]"
    return "[General]"
